### ISSUE TITLE
Mismatch MQTT topic between configuration.yaml and esp program

### ISSUE THREAD

**Issue by lorenzofattori** [LukasdeBoer/esp8266-whr930-mqtt#5]
In the home assistant configuration.yaml example:

```
    action:
      service: mqtt.publish
      data_template:
        topic: house/ventilation/whr930/set_ventilation_level
        retain: false
        payload: "{{ states('input_number.set_wtw_ventilation_level') | int }}"

and
    action:
      service: mqtt.publish
      data_template:
        topic: house/ventilation/whr930/set_temperature
        retain: false
        payload: "{{ states('input_number.set_wtw_temperature') | int }}"`
```

but in the arduino program:

```
const char* mqtt_set_ventilation_topic = "house/ventilation/whr930/setventilation";
const char* mqtt_set_temperature_topic = "house/ventilation/whr930/settemperature";
```

Result: speed and temperature don't change because the wrong topic is published.
Solution: fix the configuration.yaml file
